config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :team_assignments, only: [:new, :create, :destroy]
    resources :tasks do
      delete 'attachments/:id', to: 'tasks#destroy_attachment', as: 'attachment'
      resources :comments
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'home#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_project, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :set_task, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @task.comments.create(comment_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @comment.save
        format.html { redirect_to project_task_path(@project, @task), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to project_task_path(@project, @task), notice: "Comment was not created" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to project_task_path(@project, @task), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to project_task_path(@project, @task), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_task 
      @task = Task.find(params[:task_id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :task_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <strong>
    <%= comment.user.full_name %>
  </strong>
  <p>
    <%= comment.body %>
  </p>
</div>

app/views/comments/_form.html.erb
<% if @comment.present? %>
  <%= form_with(model: [@task.project, @task, @comment], url: project_task_comment_path(@task.project, @task, @comment), method: :patch) do |form| %>
    <%= form.hidden_field :id %>
    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.text_area :body %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% else %>
  <%= form_with(model: [@task.project, @task, @task.comments.build], url: project_task_comments_path(@task.project, @task)) do |form| %>
    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.text_area :body %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back", project_task_path(@project, @task) %>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>