config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :team_assignments, only: [:new, :create, :destroy]
    resources :tasks do
      delete 'attachments/:id', to: 'tasks#destroy_attachment', as: 'attachment'
      resources :comments
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'home#index'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :assignee, class_name: 'User', foreign_key: 'user_id', optional: true

  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :attachments, allow_destroy: true

  has_many :comments
  
  validates :name, presence: true
  validates :description, presence: true
  validates :days, presence: true
  validates :priority, presence: true
  validates :status, presence: true

  def send_task_updated_notification
    project_owner_email = project.user.email
    project_owner_name = project.user.name
    ProjectMailer.task_updated(self, project_owner_email, project_owner_name).deliver_now
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: %i[ show edit update destroy ]

  load_and_authorize_resource

  # GET /tasks or /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_tasks_url, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    if params[:task][:attachments_attributes]
      params[:task][:attachments_attributes].each do |i, attachment_params|
        if attachment_params[:_destroy] == "1"
          @task.attachments.find(attachment_params[:id]).destroy
        end
      end
    end

    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end  

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def destroy_attachment
    attachment = Attachment.find(params[:task_id])
    attachment.file.purge  # delete the attachment's file from storage
    attachment.destroy     # delete the attachment from the database
    redirect_back(fallback_location: project_task_path(@task.project, @task))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :description, :days, :days_left, :priority, :status, :project_id, :user_id, attachments_attributes: [:id, :file, :_destroy])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_assignee.html.erb
<%= form_with(model: [@project, @task], url: project_task_path(@project, @task), method: :put) do |form| %>
  <%= form.collection_select(:user_id, @project.team_members + [@project.project_manager], :id, :full_name) %>
  <%= form.submit %>
<% end %>

app/views/tasks/_file_attachment.html.erb
<%= form_with(model: [@project, @task], url: project_task_path(@project, @task), method: :put, multipart: true) do |form| %>
  <% if @task.attachments.any? %>
    <% @task.attachments.each do |attachment| %>
      <%= form.fields_for :attachments, attachment do |attachment_fields| %>
        <%= attachment_fields.hidden_field :_destroy %>
        <% if attachment.file.attached? %>
          <span class="attachment-file-name"><%= attachment.file.filename %></span>
          <% image_url = url_for(attachment.file) %>
          <%= image_tag(image_url) %>
          <%= link_to "Delete", project_task_attachment_path(@task, attachment), method: :delete, data: { confirm: "Are you sure you want to delete this attachment?" } %>
        <% else %>
          <%= attachment_fields.file_field :file %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  
  <div class="attachment-template hidden">
    <%= form.fields_for :attachments, Attachment.new do |attachment_fields| %>
      <%= attachment_fields.file_field :file %>
      <span class="attachment-file-name"></span>
    <% end %>
  </div>
  
  <div id="attachments">
    <% if @task.attachments.empty? %>
      <div class="attachment">
        <%= form.fields_for :attachments, Attachment.new do |attachment_fields| %>
          <%= attachment_fields.file_field :file %>
          <span class="attachment-file-name"></span>
        <% end %>
      </div>
    <% end %>
  </div>
  
  <%= button_to "Add Attachment", "#", class: "add-attachment" %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: [@project, @task]) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :days, style: "display: block" %>
    <%= form.number_field :days %>
  </div>

  <div>
    <%= form.label :priority, style: "display: block" %>
    <%= form.number_field :priority %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Days:</strong>
    <%= task.days %>
  </p>

  <p>
    <strong>Days left:</strong>
    <%= task.days_left %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= task.priority %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= task.status %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= task.project_id %>
  </p>
  
  <% if task.assignee.present?%>
    <p>This Task is assigned to <strong><%= task.assignee.full_name %></strong></p>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", project_task_path(@project, id: @task.id) %> |
  <%= link_to "Back to tasks", project_tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", project_task_path(id: task.id) %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_project_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", project_tasks_path %>
</div>

app/views/tasks/show.html.erb
<%= render @task %>
<% if !current_user.admin?%>
  <%= render "assignee", task: @task %>
  <%= render "file_attachment", task: @task%>
<% end %>

<div id="comments">
  <% @task.comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Edit", edit_project_task_comment_path(@project, @task, comment)%> |
      <%= link_to "Delete", project_task_comment_path(@project, @task, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>
    </p>
  <% end %>
</div>

<h1>Create Comment</h1>
<%= render partial: "comments/form", locals: { task: @task, comment: @comment } %>

<div>
  <% if !current_user.admin?%>
    <%= link_to "Edit this task", edit_project_task_path(@project, @task) %>
    <%= button_to "Destroy this task",project_task_path(@project, @task), method: :delete %>
  <% end %>
</div>

<%= link_to "Back to tasks", project_tasks_path(@project) %>