config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :team_assignments, only: [:new, :create, :destroy]
    resources :tasks do
      delete 'attachments/:id', to: 'tasks#destroy_attachment', as: 'attachment'
      resources :comments
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'home#index'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :project_manager, class_name: 'User', optional: true

  has_many :tasks
  has_many :comments

  has_many :team_assignments
  has_many :team_members, through: :team_assignments, source: :user

  after_update :send_project_updated_notification

  def send_project_updated_notification(current_user)
    project_manager_email = User.where(role: 'project_manager').pluck(:email)
    project_manager_name = User.find_by(email: project_manager_email)&.name
    ProjectMailer.project_updated(self, project_manager_email, project_manager_name, current_user).deliver_now
  end 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects.all
    @project_manager_projects = Project.where(project_manager_id: current_user.id)
    @team_member_projects = TeamAssignment.joins(:project).where(user_id: current_user.id)
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project_team_members = @project.team_members
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :start_date, :end_date, :project_manager_id).merge(user_id: current_user.id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :project_manager_id %>
    <%= form.collection_select :project_manager_id, User.where(role: "project_manager"), :id, ->(user) { "#{user.first_name} #{user.last_name}" }, prompt: "Select Project Manager" %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= project.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= project.end_date %>
  </p>

  <% if project.project_manager.present?%>
    <p>
      <strong>Project Manager:</strong>
      <%= project.project_manager.first_name%>  <%= project.project_manager.last_name%>
    </p>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<% @project_manager_projects.each do |project|%>
  <%= render project %>
  <p>
    <%= link_to "Show this project", project %>
  </p>
<% end%>

<% @team_member_projects.each do |team_assignment|%>
  <%= render partial: "team_assignments/team_assignment", locals: { project: team_assignment.project } %>
<% end%>

<% if current_user.admin?%>
  <%= link_to "New project", new_project_path %>
<% end%>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<%= render @project %>

<h3>Team Members</h3>
<ol>
  <% @project_team_members.each do |member| %>
    <li><%= member.full_name%></li>
  <% end %>
</ol>

<div>
  <% if current_user.admin?%>
    <%= link_to 'Assign team member', new_project_team_assignment_path(project_id: @project.id) %>
    <%= link_to "Edit this project", edit_project_path(@project) %> |
    <%= button_to "Destroy this project", @project, method: :delete %>
  <% end %>
  <%= link_to "Tasks", project_tasks_path(@project) %>
  <%= link_to "Back to projects", projects_path %>
</div>