config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :team_assignments, only: [:new, :create, :destroy]
    resources :tasks do
      delete 'attachments/:id', to: 'tasks#destroy_attachment', as: 'attachment'
      resources :comments
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'home#index'
end

app/models/team_assignment.rb
class TeamAssignment < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/controllers/team_assignments_controller.rb
class TeamAssignmentsController < ApplicationController
  load_and_authorize_resource

  def new
    @project = Project.find(params[:project_id])
  end

  def create
    @project = Project.find(params[:project_id])
    @team_assignment = @project.team_assignments.build(team_assignment_params)

    if @team_assignment.save
      redirect_to @project, notice: 'Team member assigned successfully.'
    else
      render :new
    end
  end

  private

  def team_assignment_params
    params.require(:team_assignment).permit(:user_id)
  end
end

app/helpers/team_assignments_helper.rb
module TeamAssignmentsHelper
end

app/views/team_assignments/_team_assignment.html.erb
<li><%= link_to project.name, project_path(project) %></li>

app/views/team_assignments/new.html.erb
# app/views/team_assignments/new.html.erb
<h1>New Team Assignment</h1>

<%= form_with(model: [@project, @team_assignment], url: project_team_assignments_path(@project)) do |form| %>
  <%= form.label :user_id, 'Team member' %>
  <%= form.collection_select :user_id, User.where(role: "team_member"), :id, ->(user) { user.full_name }, prompt: "Assign team member" %>
  <%= form.submit 'Assign team member' %>
<% end %>